runtime: nodejs10
service: "default"
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
health_check:
  enable_health_check: False
instance_class: F2
automatic_scaling:
  max_instances: 2
  target_cpu_utilization: 0.7
